cookie-sqli/app/flaskr/models.py
# empty

cookie-sqli/app/flaskr/__init__.py
from flaskr.app import (
    create_app
)

cookie-sqli/app/flaskr/app.py
import os
import sys

from flask import Flask
from sqlalchemy import create_engine


class ConfigClass(object):
    DEBUG = True
    SECRET_KEY = os.environ.get('SECRET_KEY', 'A_DEFAULT_SECRET_KEY_OH_NO')
    TITLE = "NSA Admin Portal"
    NAVBAR = []
    LOGIN_FORM = True
    THEME = "flatly"
    STATIC_URL_PATH = "/static"

    try:
        FLAG = os.environ['FLAG']
        FLAG_SECRET = os.environ['FLAG_SECRET']
        DB_CONNECTION_STRING = os.environ['DB_CONNECTION_STRING']
    except KeyError as e:
        if "pytest" not in sys.modules:
            raise e

        FLAG = "IF_I_SEE_THIS_THIS_AINT_PATCHED"
        FLAG_SECRET = "lolno"


def register_models(app):
    from . import models


def register_blueprints(app):
    from .basic import app as basic_bp
    app.register_blueprint(basic_bp)


def create_app():
    app = Flask(__name__)
    app.config.from_object(__name__ + '.ConfigClass')

    register_models(app)
    register_blueprints(app)

    # setup our database connection
    if 'DB_CONNECTION_STRING' in app.config:
        app.db = create_engine(app.config['DB_CONNECTION_STRING'])

    return app

cookie-sqli/app/flaskr/basic/__init__.py
from flask import Blueprint

app = Blueprint(
    'basic',
    __name__,
    template_folder='templates',
    static_folder='static',
    static_url_path='/static/basic')

from . import views

cookie-sqli/app/flaskr/basic/views.py
import re
import datetime

from flask import render_template_string, request, render_template, current_app, flash, redirect, url_for, session, make_response
from . import app


def isLoggedIn(session):
    r = current_app.db.execute(f"select * from admins where session = '{session}'").first()
    return r != None

@app.route('/', methods=["GET","POST"])
def home():
    # check cookie via db
    if isLoggedIn(request.cookies.get("session","123")):
        return render_template("flag.html")
    
    if request.method == "POST":
        # you can't just login lol use some sqli fuckboi
        flash('Unknown Username/Password', 'danger')
    resp = make_response(render_template("home.html"))
    resp.set_cookie('session', '123')
    return resp


@app.route('/ping')
def ping():
    return "pong"


@app.route('/flag_debug', methods=["POST"])
def flag_debug():
    if request.form.get("flag_secret", "") == current_app.config['FLAG_SECRET']:
        return current_app.config['FLAG']
    return ":(", 401

cookie-sqli/app/flaskr/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://bootswatch.com/4/{{config['THEME']}}/bootstrap.min.css" crossorigin="anonymous">

    <title>{{config["TITLE"]}}</title>

    <!-- Style Overrides -->
    <style>
    .link-override{
      color: white;
      margin-left: 1rem;
      margin-right: 1rem;
    }
    .link-override:hover {
      color: #00bc8c;
      text-decoration: none;
    }
    .container {
      margin-top: 1rem;
    }
    </style>
  </head>
  <body>
      <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
        <a class="navbar-brand" href="{{url_for('basic.home')}}">{{config["TITLE"]}}</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse" id="navbarColor01">
            <ul class="navbar-nav mr-auto">
              {% for link in config["NAVBAR"]%}
              <li class="nav-item active">
                <a class="link-override" href="{{link[1]}}">{{link[0]}}</a>
              </li>
              {% endfor %}
            </ul>
            {% if config["LOGIN_FORM"] %}
            <form class="form-inline my-2 my-lg-0" method="POST">
              <input name="email" class="form-control mr-sm-2" type="text" placeholder="Email">
              <input name="password" class="form-control mr-sm-2" type="password" placeholder="Password">
              <button class="btn btn-secondary my-2 my-sm-0" type="submit">Login</button>
            </form>
            {% endif %}
          </div>
        </nav>

    <div class="container">
    {% with messages = get_flashed_messages(with_categories=true) %}
      {% if messages %}
        {% for category, message in messages %}
          <div class="alert alert-dismissible alert-{{category}}">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            <p class="mb-0">{{message}}</p>
          </div>
        {% endfor %}
      {% endif %}
    {% endwith %}

    {% block content %}

    {% endblock content %}
    </div>

    {#
    <div style="position: fixed; bottom: 0px; padding-bottom: 30px; width: 100%; text-align: center">
      <small id="emailHelp" class="form-text text-muted">Your IP is being recorded. Our automated systems keep track of your IP and any detected relevant information. <br>Contact z9447944@cse.unsw.edu.au for any assistance.</small>
    </div>
    #}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  </body>
</html>